### ISSUE TITLE
generation of contact file 

### ISSUE THREAD

**Issue by Tom43-sys** [RomeroLab/Golden-Gate-SCHEMA-RASPP#1]
Dear Romero's Lab
I was wondering if the script step1 had been used for the generation of contacts file in the following paper (Ojala et al. Mol Ther 2018 10.1016/j.ymthe.2017.09.006) for the intra- and inter-subunit amino acid contacts.
If not, could you please share the script? 

Sincerely,
Thomas

**Comment by bbremer** [comment]
Hi Thomas,

The script is not the exact same as the one used for the paper, but they're essentially the same thing. The relevant lines would be 108-119 in step_1.py. Note that this script does not distinguish between intra- and inter-subunit contacts, it reads all amino acids in the PDB without considering subunits. Please let us know if this is sufficient and/or you have questions.

Thanks,
ben

**Comment by Tom43-sys** [comment]
Hi Ben,

Thanks a lot for your quick answer. I'll use the script for my research.

Cheers,
Thomas
